on:
  workflow_call:
jobs:
  BuildAndRelease:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: false   #set-safe-directory option of checkout didn't work
          fetch-depth: 0
          token: ${{ secrets.CFD_GIT_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.CFD_GIT_USER }}
          git config --global user.email ${{ secrets.CFD_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: CheckCRCSubmodule
        run: |
          echo "Check central-common"
          if cat .gitmodules | grep central-common > /dev/null ; then
            rm -rf central-common
            git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common central-common
            echo -e "\e[92m central-common is added \e[0m"
          else
            echo -e "\e[31m central-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckB2PSubmodule
        run: |
          echo "Check b2p-common"
          if cat .gitmodules | grep b2p-common > /dev/null ; then
            rm -rf b2p-common
            git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
            echo -e "\e[92m b2p-common is added \e[0m"
          else
            echo -e "\e[31m b2p-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckCFDSubmodule
        run: |
          echo "Check cfd-common"
          if cat .gitmodules | grep cfd-common > /dev/null ; then
            rm -rf cfd-common
            git submodule add --force --name cfd-common https://${{ secrets.CFD_GIT_USER }}:${{ secrets.CFD_GIT_TOKEN }}@github.com/digital-ventures/cfd-common cfd-common
            echo -e "\e[92m cfd-common is added \e[0m"
          else
            echo -e "\e[31m cfd-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckSubmoduleExited
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".gitmodules"

      - name: UpdateSubmodule
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CFD_ACR_REGISTRY }}
          username: ${{ secrets.CFD_ACR_USER }}
          password: ${{ secrets.CFD_ACR_TOKEN }}
          
      - name: RemoveFilesBeforeBuild
        run:
          rm -rf ./src/main/resources/application.yml
          rm -rf ./src/main/resources/application.properties

      - name: BuildImage
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: |
              jib
              --image=${{ secrets.CFD_ACR_REGISTRY }}/backend/${{ secrets.CFD_SERVICENAME }}:${{ github.ref_name }}
